export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERS_NOT_FOUND: 'USERS_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
  USER_DELETION_FAILED: 'USER_DELETION_FAILED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  REFRESH_TOKEN_INVALID_OR_EXPIRED: 'REFRESH_TOKEN_INVALID_OR_EXPIRED',
  USER_CREATION_FAILED: 'USER_CREATION_FAILED',
  INVALID_UUID: 'INVALID_UUID',
} as const;

export type ErrorCodes = typeof ERROR_CODES[keyof typeof ERROR_CODES];
